version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress:ro
      - nginx_data:/etc/nginx/ssl
      - ./requirements/nginx/tools/default.conf:/etc/nginx/http.d/default.conf:ro
    networks:
      - inception


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress
      o: bind

  nginx_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/nginx
      o: bind


networks:
  inception:
    driver: bridge
